stepback: true
command_type: test
ignore:
  - "*.md"
  - ".github/*"

#######################################
#              Functions              #
#######################################
functions:
  attach-test-results:
    command: attach.xunit_results
    params:
      files:
        - "./parsley/bin/jest/*.xml"
  
  get-project:
    command: git.get_project
    type: setup
    params:
      directory: parsley

  yarn-install:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn

  yarn-build:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn build:local

  yarn-tsc:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn check-types

  yarn-eslint:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn eslint:strict

  yarn-snapshot:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn test --ci --testPathPattern=storybook.test.ts

  yarn-storybook:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn storybook:build

  yarn-test:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn test --ci --testPathIgnorePatterns=storybook.test.ts


#######################################
#                Tasks                #
#######################################
tasks:
  - name: compile
    commands:
    - func: yarn-build

  - name: type_check
    commands:
    - func: yarn-tsc

  - name: lint
    commands:
    - func: yarn-eslint

  - name: test
    commands:
    - func: yarn-test
    - func: attach-test-results

  - name: storybook
    commands:
    - func: yarn-storybook

  - name: snapshots
    commands:
    - func: yarn-snapshot
    - func: attach-test-results

buildvariants:
  - name: ubuntu1604
    display_name: Ubuntu 16.04
    run_on:
    - ubuntu1604-small
    tasks:
    - name: compile
    - name: type_check
    - name: lint
    - name: test
    - name: storybook
    - name: snapshots

pre:
  - func: get-project
  - func: yarn-install