stepback: true
command_type: test
ignore:
  - "*.md"
  - ".github/*"

#######################################
#              Functions              #
#######################################
functions:
  get-project:
    command: git.get_project
    type: setup
    params:
      directory: parsley

  yarn-install:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn

  yarn-eslint:
    command: shell.exec
    params:
      working_dir: parsley
      script: |
        export PATH=${node_path}
        yarn eslint:strict

#######################################
#                Tasks                #
#######################################
tasks:
  - name: lint
    commands:
    - func: get-project
    - func: yarn-install
    - func: yarn-eslint

buildvariants:
  - name: ubuntu1604
    display_name: Ubuntu 16.04
    run_on:
    - ubuntu1604-small
    tasks:
    - name: lint